apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrations
  namespace: flamoral
  labels:
    app: flamoral
    component: migrations
spec:
  ttlSecondsAfterFinished: 600
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrations
          image: 992382449461.dkr.ecr.us-east-1.amazonaws.com/flamoral/user-service:latest
          imagePullPolicy: Always
          command: ["npm", "run", "migrate"]
          env:
            - name: NODE_ENV
              value: "production"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: DATABASE_URL
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      backoffLimit: 3
