apiVersion: v1
kind: Secret
metadata:
  name: flamoral-secrets
  namespace: flamoral
type: Opaque
stringData:
  JWT_ACCESS_SECRET: "flamoral-jwt-access-secret-key-2024-production"
  JWT_REFRESH_SECRET: "flamoral-jwt-refresh-secret-key-2024"
  JWT_SECRET: "flamoral-jwt-secret-key-2024-production"
  ENCRYPTION_KEY: "flamoral-encryption-key-32-chars!"
  DATABASE_URL: "postgresql://flamoral:Flamoral2024Secure!@postgres:5432/flamoral_db"
  POSTGRES_PASSWORD: "Flamoral2024Secure!"
  REDIS_URL: "redis://redis:6379"
  SERVICE_API_KEY: "flamoral-internal-service-api-key-2024"
