import { Knex } from 'knex';
import * as bcrypt from 'bcrypt';

/**
 * Seed: Development Users and Profiles
 * Creates sample users and profiles for testing
 */
export async function seed(knex: Knex): Promise<void> {
  // Clear existing data (in reverse order of dependencies)
  await knex('user_prompts').del();
  await knex('photos').del();
  await knex('user_preferences').del();
  await knex('messages').del();
  await knex('conversations').del();
  await knex('matches').del();
  await knex('swipes').del();
  await knex('verification_tokens').del();
  await knex('refresh_tokens').del();
  await knex('profiles').del();
  await knex('users').del();

  // Create password hash for all test users
  const passwordHash = await bcrypt.hash('Test123!', 10);

  // Sample users data
  const users = [
    {
      id: '550e8400-e29b-41d4-a716-446655440001',
      email: 'alice.johnson@example.com',
      password_hash: passwordHash,
      phone_number: '+1234567890',
      status: 'active',
      subscription_tier: 'ultra',
      is_email_verified: true,
      is_phone_verified: true,
      is_photo_verified: true,
      last_login_at: knex.fn.now(),
      last_active_at: knex.fn.now(),
    },
    {
      id: '550e8400-e29b-41d4-a716-446655440002',
      email: 'bob.smith@example.com',
      password_hash: passwordHash,
      phone_number: '+1234567891',
      status: 'active',
      subscription_tier: 'mid',
      is_email_verified: true,
      is_phone_verified: true,
      is_photo_verified: false,
      last_login_at: knex.fn.now(),
      last_active_at: knex.fn.now(),
    },
    {
      id: '550e8400-e29b-41d4-a716-446655440003',
      email: 'carol.williams@example.com',
      password_hash: passwordHash,
      phone_number: '+1234567892',
      status: 'active',
      subscription_tier: 'basic',
      is_email_verified: true,
      is_phone_verified: false,
      is_photo_verified: true,
      last_login_at: knex.fn.now(),
      last_active_at: knex.fn.now(),
    },
    {
      id: '550e8400-e29b-41d4-a716-446655440004',
      email: 'david.brown@example.com',
      password_hash: passwordHash,
      phone_number: '+1234567893',
      status: 'active',
      subscription_tier: 'free',
      is_email_verified: true,
      is_phone_verified: false,
      is_photo_verified: false,
      last_login_at: knex.fn.now(),
      last_active_at: knex.fn.now(),
    },
    {
      id: '550e8400-e29b-41d4-a716-446655440005',
      email: 'emily.davis@example.com',
      password_hash: passwordHash,
      phone_number: '+1234567894',
      status: 'active',
      subscription_tier: 'mid',
      is_email_verified: true,
      is_phone_verified: true,
      is_photo_verified: true,
      last_login_at: knex.fn.now(),
      last_active_at: knex.fn.now(),
    },
    {
      id: '550e8400-e29b-41d4-a716-446655440006',
      email: 'frank.miller@example.com',
      password_hash: passwordHash,
      phone_number: '+1234567895',
      status: 'active',
      subscription_tier: 'basic',
      is_email_verified: true,
      is_phone_verified: true,
      is_photo_verified: false,
      last_login_at: knex.fn.now(),
      last_active_at: knex.fn.now(),
    },
  ];

  await knex('users').insert(users);

  // Sample profiles data
  const profiles = [
    {
      user_id: '550e8400-e29b-41d4-a716-446655440001',
      first_name: 'Alice',
      last_name: 'Johnson',
      date_of_birth: '1995-05-15',
      gender: 'female',
      bio: 'Adventure seeker and coffee enthusiast. Love hiking, photography, and trying new cuisines!',
      occupation: 'Software Engineer',
      education: 'Masters in Computer Science',
      company: 'Tech Innovations Inc.',
      school: 'Stanford University',
      height: 165,
      city: 'San Francisco',
      state: 'California',
      country: 'United States',
      latitude: 37.7749,
      longitude: -122.4194,
      interests: JSON.stringify(['hiking', 'photography', 'cooking', 'yoga', 'travel']),
      languages: JSON.stringify(['English', 'Spanish', 'French']),
      relationship_type: 'long_term',
      profile_completion_percentage: 95,
    },
    {
      user_id: '550e8400-e29b-41d4-a716-446655440002',
      first_name: 'Bob',
      last_name: 'Smith',
      date_of_birth: '1992-08-22',
      gender: 'male',
      bio: 'Fitness enthusiast and dog lover. Looking for someone to share adventures with!',
      occupation: 'Personal Trainer',
      education: 'Bachelors in Kinesiology',
      company: 'FitLife Gym',
      school: 'UCLA',
      height: 180,
      city: 'Los Angeles',
      state: 'California',
      country: 'United States',
      latitude: 34.0522,
      longitude: -118.2437,
      interests: JSON.stringify(['fitness', 'dogs', 'running', 'nutrition', 'basketball']),
      languages: JSON.stringify(['English']),
      relationship_type: 'long_term',
      profile_completion_percentage: 85,
    },
    {
      user_id: '550e8400-e29b-41d4-a716-446655440003',
      first_name: 'Carol',
      last_name: 'Williams',
      date_of_birth: '1997-03-10',
      gender: 'female',
      bio: 'Artist and bookworm. Netflix marathons are my specialty. Cat mom to two adorable furballs.',
      occupation: 'Graphic Designer',
      education: 'BFA in Graphic Design',
      company: 'Creative Studios',
      school: 'Rhode Island School of Design',
      height: 170,
      city: 'New York',
      state: 'New York',
      country: 'United States',
      latitude: 40.7128,
      longitude: -74.0060,
      interests: JSON.stringify(['art', 'reading', 'cats', 'movies', 'design', 'coffee']),
      languages: JSON.stringify(['English', 'Italian']),
      relationship_type: 'casual',
      profile_completion_percentage: 90,
    },
    {
      user_id: '550e8400-e29b-41d4-a716-446655440004',
      first_name: 'David',
      last_name: 'Brown',
      date_of_birth: '1990-11-05',
      gender: 'male',
      bio: 'Music producer and vinyl collector. Always looking for the next great concert.',
      occupation: 'Music Producer',
      education: 'Bachelors in Music Production',
      company: 'SoundWave Studios',
      school: 'Berklee College of Music',
      height: 175,
      city: 'Austin',
      state: 'Texas',
      country: 'United States',
      latitude: 30.2672,
      longitude: -97.7431,
      interests: JSON.stringify(['music', 'concerts', 'vinyl', 'guitar', 'songwriting']),
      languages: JSON.stringify(['English']),
      relationship_type: 'open_to_anything',
      profile_completion_percentage: 75,
    },
    {
      user_id: '550e8400-e29b-41d4-a716-446655440005',
      first_name: 'Emily',
      last_name: 'Davis',
      date_of_birth: '1994-07-18',
      gender: 'female',
      bio: 'Foodie and travel blogger. My passport is my most prized possession!',
      occupation: 'Travel Blogger',
      education: 'Bachelors in Journalism',
      company: 'Self-employed',
      school: 'Northwestern University',
      height: 168,
      city: 'Chicago',
      state: 'Illinois',
      country: 'United States',
      latitude: 41.8781,
      longitude: -87.6298,
      interests: JSON.stringify(['travel', 'food', 'blogging', 'photography', 'culture']),
      languages: JSON.stringify(['English', 'Portuguese', 'Japanese']),
      relationship_type: 'long_term',
      profile_completion_percentage: 100,
    },
    {
      user_id: '550e8400-e29b-41d4-a716-446655440006',
      first_name: 'Frank',
      last_name: 'Miller',
      date_of_birth: '1993-12-30',
      gender: 'male',
      bio: 'Tech entrepreneur and gamer. Building the next big thing. Pizza connoisseur.',
      occupation: 'Startup Founder',
      education: 'Bachelors in Business Administration',
      company: 'NextGen Tech',
      school: 'MIT',
      height: 178,
      city: 'Seattle',
      state: 'Washington',
      country: 'United States',
      latitude: 47.6062,
      longitude: -122.3321,
      interests: JSON.stringify(['technology', 'gaming', 'entrepreneurship', 'pizza', 'coding']),
      languages: JSON.stringify(['English', 'Mandarin']),
      relationship_type: 'short_term',
      profile_completion_percentage: 80,
    },
  ];

  await knex('profiles').insert(profiles);

  // Sample user preferences
  const preferences = [
    {
      user_id: '550e8400-e29b-41d4-a716-446655440001',
      age_min: 25,
      age_max: 35,
      max_distance: 50,
      gender_preference: JSON.stringify(['male']),
      relationship_type_preference: JSON.stringify(['long_term', 'casual']),
      show_me_on_discover: true,
      premium_only: false,
      verified_only: true,
      min_height: 175,
      max_height: 190,
    },
    {
      user_id: '550e8400-e29b-41d4-a716-446655440002',
      age_min: 22,
      age_max: 32,
      max_distance: 30,
      gender_preference: JSON.stringify(['female']),
      relationship_type_preference: JSON.stringify(['long_term']),
      show_me_on_discover: true,
      premium_only: false,
      verified_only: false,
      min_height: 160,
      max_height: 175,
    },
    {
      user_id: '550e8400-e29b-41d4-a716-446655440003',
      age_min: 24,
      age_max: 38,
      max_distance: 25,
      gender_preference: JSON.stringify(['male']),
      relationship_type_preference: JSON.stringify(['casual', 'short_term']),
      show_me_on_discover: true,
      premium_only: false,
      verified_only: false,
      min_height: 170,
      max_height: 185,
    },
    {
      user_id: '550e8400-e29b-41d4-a716-446655440004',
      age_min: 20,
      age_max: 30,
      max_distance: 40,
      gender_preference: JSON.stringify(['female']),
      relationship_type_preference: JSON.stringify(['open_to_anything']),
      show_me_on_discover: true,
      premium_only: false,
      verified_only: false,
    },
    {
      user_id: '550e8400-e29b-41d4-a716-446655440005',
      age_min: 26,
      age_max: 36,
      max_distance: 60,
      gender_preference: JSON.stringify(['male']),
      relationship_type_preference: JSON.stringify(['long_term']),
      show_me_on_discover: true,
      premium_only: false,
      verified_only: true,
      min_height: 175,
    },
    {
      user_id: '550e8400-e29b-41d4-a716-446655440006',
      age_min: 21,
      age_max: 28,
      max_distance: 35,
      gender_preference: JSON.stringify(['female', 'non-binary']),
      relationship_type_preference: JSON.stringify(['short_term', 'casual']),
      show_me_on_discover: true,
      premium_only: false,
      verified_only: false,
    },
  ];

  await knex('user_preferences').insert(preferences);

  console.log('✓ Seeded users, profiles, and preferences');
}
