import { Controller, Get, Req, Res } from '@nestjs/common';
import { ApiTags, ApiOperation, ApiResponse } from '@nestjs/swagger';
import { Request, Response } from 'express';
import { Public } from '../decorators/public.decorator';
import { CsrfToken } from '../decorators/csrf.decorator';

/**
 * CSRF Token Controller
 *
 * Provides endpoints for obtaining CSRF tokens
 */
@ApiTags('security')
@Controller('csrf')
export class CsrfController {
  /**
   * Get CSRF Token
   *
   * Returns a CSRF token that clients should include in state-changing requests
   * The token is also available in the XSRF-TOKEN cookie
   */
  @Public()
  @CsrfToken()
  @Get('token')
  @ApiOperation({
    summary: 'Get CSRF token',
    description: 'Returns a CSRF token for use in subsequent requests. The token is also set as a cookie.',
  })
  @ApiResponse({
    status: 200,
    description: 'CSRF token successfully generated',
    schema: {
      type: 'object',
      properties: {
        csrfToken: {
          type: 'string',
          description: 'The CSRF token to include in request headers',
          example: 'a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6',
        },
        headerName: {
          type: 'string',
          description: 'The name of the header to send the token in',
          example: 'X-CSRF-Token',
        },
      },
    },
  })
  getCsrfToken(@Req() req: Request): { csrfToken: string; headerName: string } {
    // The token is generated by the CSRF middleware
    const token = req.csrfToken ? req.csrfToken() : '';

    return {
      csrfToken: token,
      headerName: 'X-CSRF-Token',
    };
  }

  /**
   * Verify CSRF Token
   *
   * Allows clients to verify their CSRF token is valid
   * Useful for debugging and testing
   */
  @Public()
  @Get('verify')
  @ApiOperation({
    summary: 'Verify CSRF token',
    description: 'Verify that the provided CSRF token is valid',
  })
  @ApiResponse({
    status: 200,
    description: 'Token verification result',
    schema: {
      type: 'object',
      properties: {
        valid: {
          type: 'boolean',
          description: 'Whether the token is valid',
        },
        message: {
          type: 'string',
          description: 'Verification message',
        },
      },
    },
  })
  verifyToken(@Req() req: Request): { valid: boolean; message: string } {
    const cookieToken = req.cookies?.['XSRF-TOKEN'];
    const headerToken = req.headers['x-csrf-token'] as string;

    if (!cookieToken) {
      return {
        valid: false,
        message: 'No CSRF token found in cookies',
      };
    }

    if (!headerToken) {
      return {
        valid: true,
        message: 'CSRF token exists in cookie. Include it in the X-CSRF-Token header for state-changing requests.',
      };
    }

    const valid = cookieToken === headerToken;

    return {
      valid,
      message: valid
        ? 'CSRF token is valid'
        : 'CSRF token mismatch between cookie and header',
    };
  }
}
