#!/bin/bash

# =============================================================================
# Install Git Hooks - Flamoral Dating Platform
# =============================================================================
# Installs pre-commit hook for local secret scanning
# Usage: ./scripts/install-git-hooks.sh
# =============================================================================

set -e

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
HOOKS_DIR="$REPO_ROOT/.git/hooks"
PRE_COMMIT_HOOK="$HOOKS_DIR/pre-commit"

echo "==================================================================="
echo "Flamoral Git Hooks Installer"
echo "==================================================================="
echo ""

# Check if Gitleaks is installed
if ! command -v gitleaks &> /dev/null; then
    echo "⚠️  WARNING: Gitleaks is not installed!"
    echo ""
    echo "To install Gitleaks:"
    echo ""
    echo "  macOS:    brew install gitleaks"
    echo "  Windows:  choco install gitleaks"
    echo "  Linux:    See https://github.com/gitleaks/gitleaks#installing"
    echo ""
    read -p "Continue without Gitleaks? (y/N) " -n 1 -r
    echo ""
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Installation cancelled."
        exit 1
    fi
    GITLEAKS_INSTALLED=false
else
    echo "✅ Gitleaks is installed: $(gitleaks version)"
    GITLEAKS_INSTALLED=true
fi

echo ""

# Check if .git directory exists
if [ ! -d "$REPO_ROOT/.git" ]; then
    echo "❌ ERROR: Not a git repository!"
    echo "Please run this script from the root of the repository."
    exit 1
fi

# Create hooks directory if it doesn't exist
mkdir -p "$HOOKS_DIR"

# Backup existing pre-commit hook if it exists
if [ -f "$PRE_COMMIT_HOOK" ]; then
    echo "📦 Backing up existing pre-commit hook..."
    cp "$PRE_COMMIT_HOOK" "$PRE_COMMIT_HOOK.backup.$(date +%Y%m%d_%H%M%S)"
    echo "   Backup saved to: $PRE_COMMIT_HOOK.backup.*"
    echo ""
fi

# Create pre-commit hook
echo "📝 Creating pre-commit hook..."

cat > "$PRE_COMMIT_HOOK" << 'EOF'
#!/bin/bash

# =============================================================================
# Pre-commit Hook - Secret Scanning
# =============================================================================
# Automatically scans staged files for secrets before allowing commit
# Generated by: scripts/install-git-hooks.sh
# =============================================================================

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo ""
echo "🔍 Running pre-commit secret scan..."
echo ""

# Check if Gitleaks is installed
if ! command -v gitleaks &> /dev/null; then
    echo -e "${YELLOW}⚠️  WARNING: Gitleaks is not installed!${NC}"
    echo "Secret scanning will be skipped locally, but will run in CI."
    echo ""
    echo "To install Gitleaks:"
    echo "  macOS:    brew install gitleaks"
    echo "  Windows:  choco install gitleaks"
    echo "  Linux:    See https://github.com/gitleaks/gitleaks#installing"
    echo ""
    exit 0
fi

# Get repository root
REPO_ROOT="$(git rev-parse --show-toplevel)"

# Check if .gitleaks.toml exists
if [ ! -f "$REPO_ROOT/.gitleaks.toml" ]; then
    echo -e "${YELLOW}⚠️  WARNING: .gitleaks.toml not found!${NC}"
    echo "Using default Gitleaks configuration."
    CONFIG_ARG=""
else
    CONFIG_ARG="--config=$REPO_ROOT/.gitleaks.toml"
fi

# Run Gitleaks on staged changes
echo "Scanning staged changes..."
if gitleaks protect $CONFIG_ARG --verbose --staged --redact 2>&1 | tee /tmp/gitleaks-output.txt; then
    echo ""
    echo -e "${GREEN}✅ No secrets detected!${NC}"
    echo "Proceeding with commit..."
    echo ""
    exit 0
else
    EXIT_CODE=$?
    echo ""
    echo -e "${RED}❌ SECRETS DETECTED!${NC}"
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo -e "${RED}🚫 COMMIT BLOCKED - Please fix the issues above${NC}"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "What to do:"
    echo "  1. Review the detected secrets above"
    echo "  2. Remove secrets from your code"
    echo "  3. Move secrets to .env file (not committed)"
    echo "  4. Use environment variables in your code"
    echo "  5. Try committing again"
    echo ""
    echo "If this is a false positive:"
    echo "  1. Add pattern to .gitleaks.toml allowlist"
    echo "  2. Document why it's safe"
    echo "  3. Try committing again"
    echo ""
    echo "To bypass this check (NOT RECOMMENDED):"
    echo "  git commit --no-verify"
    echo ""
    echo "For help, see: docs/security/SECRET-SCANNING-GUIDE.md"
    echo ""

    # Clean up
    rm -f /tmp/gitleaks-output.txt

    exit $EXIT_CODE
fi
EOF

# Make hook executable
chmod +x "$PRE_COMMIT_HOOK"

echo "✅ Pre-commit hook installed successfully!"
echo ""

# Test the hook
if [ "$GITLEAKS_INSTALLED" = true ]; then
    echo "🧪 Testing the hook..."
    echo ""

    # Create a temporary test file
    TEST_FILE="$REPO_ROOT/.git/test_secret_scan.tmp"
    echo "STRIPE_SECRET_KEY=sk_live_test123456789" > "$TEST_FILE"
    git add "$TEST_FILE" 2>/dev/null || true

    if gitleaks protect --config="$REPO_ROOT/.gitleaks.toml" --verbose --staged --redact &> /dev/null; then
        echo "✅ Hook is working correctly!"
    else
        echo "✅ Hook is working correctly (detected test secret)!"
    fi

    # Clean up test file
    git reset -- "$TEST_FILE" 2>/dev/null || true
    rm -f "$TEST_FILE"
    echo ""
fi

echo "==================================================================="
echo "Installation Complete!"
echo "==================================================================="
echo ""
echo "The pre-commit hook will now:"
echo "  ✅ Scan staged files for secrets before each commit"
echo "  ✅ Block commits if secrets are detected"
echo "  ✅ Provide instructions for remediation"
echo ""
echo "To bypass the hook (NOT RECOMMENDED):"
echo "  git commit --no-verify"
echo ""
echo "To uninstall the hook:"
echo "  rm $PRE_COMMIT_HOOK"
echo ""
echo "For more information:"
echo "  docs/security/SECRET-SCANNING-GUIDE.md"
echo ""
