import { IsString, IsUUID, IsEnum, IsOptional, IsInt, Min, Max } from 'class-validator';
import { Type } from 'class-transformer';

/**
 * Supported call types
 */
export enum CallType {
  VIDEO = 'video',
  AUDIO = 'audio',
}

/**
 * DTO for requesting a call
 * POST /api/v1/calls/request
 *
 * Server-owned fields NOT included:
 * - callerId (extracted from auth token)
 * - callId (generated by server)
 * - channelName (generated by server)
 * - status (set by server)
 * - startTime, endTime, duration (server-managed)
 */
export class RequestCallDto {
  @IsUUID()
  calleeId: string;

  @IsEnum(CallType, {
    message: 'callType must be either "video" or "audio"',
  })
  callType: CallType;
}

/**
 * DTO for accepting a call
 * POST /api/v1/calls/accept
 */
export class AcceptCallDto {
  @IsUUID()
  callId: string;
}

/**
 * DTO for rejecting a call
 * POST /api/v1/calls/reject
 */
export class RejectCallDto {
  @IsUUID()
  callId: string;

  @IsOptional()
  @IsString()
  reason?: string;
}

/**
 * DTO for ending a call
 * POST /api/v1/calls/end
 */
export class EndCallDto {
  @IsUUID()
  callId: string;

  @IsOptional()
  @IsInt()
  @Min(0)
  @Type(() => Number)
  duration?: number;
}

/**
 * DTO for call history pagination
 * GET /api/v1/calls/history
 */
export class CallHistoryQueryDto {
  @IsOptional()
  @IsInt()
  @Min(1)
  @Max(100)
  @Type(() => Number)
  limit?: number = 50;

  @IsOptional()
  @IsInt()
  @Min(0)
  @Type(() => Number)
  offset?: number = 0;
}
