import { IsUUID, IsOptional, IsInt, Min, Max } from 'class-validator';
import { Type } from 'class-transformer';

/**
 * DTO for creating a new conversation
 * POST /api/conversations
 *
 * Server-owned fields NOT included:
 * - id (generated by server)
 * - participant1Id (extracted from auth token as creator)
 * - createdAt, updatedAt (server timestamps)
 * - status (defaults to ACTIVE)
 * - lastMessageId, lastMessageAt, lastMessagePreview (server-managed)
 * - unreadCount (server-managed)
 */
export class CreateConversationDto {
  @IsUUID()
  participantId: string;
}

/**
 * DTO for pagination query parameters
 * Used in GET /api/conversations and GET /api/conversations/:conversationId/messages
 */
export class ConversationPaginationDto {
  @IsOptional()
  @IsInt()
  @Min(1)
  @Max(100)
  @Type(() => Number)
  limit?: number = 50;

  @IsOptional()
  @IsInt()
  @Min(0)
  @Type(() => Number)
  offset?: number = 0;
}

/**
 * DTO for getting messages with pagination
 * GET /api/conversations/:conversationId/messages
 */
export class GetMessagesQueryDto extends ConversationPaginationDto {}
