import {
  IsString,
  IsUUID,
  IsInt,
  IsArray,
  IsOptional,
  ValidateNested,
  ArrayMinSize,
  Min,
  Max,
} from 'class-validator';
import { Type } from 'class-transformer';

/**
 * DTO for identity key pair
 */
export class IdentityKeyDto {
  @IsString()
  publicKey: string;

  @IsOptional()
  @IsString()
  privateKey?: string;
}

/**
 * DTO for signed pre-key
 */
export class SignedPreKeyDto {
  @IsInt()
  @Min(0)
  keyId: number;

  @IsString()
  publicKey: string;

  @IsOptional()
  @IsString()
  privateKey?: string;

  @IsString()
  signature: string;

  @IsOptional()
  timestamp?: number | string;
}

/**
 * DTO for one-time pre-key
 */
export class OneTimePreKeyDto {
  @IsInt()
  @Min(0)
  keyId: number;

  @IsString()
  publicKey: string;

  @IsOptional()
  @IsString()
  privateKey?: string;
}

/**
 * DTO for uploading encryption keys bundle
 * POST /api/keys/upload
 *
 * Server-owned fields NOT included:
 * - userId (extracted from auth token)
 * - id (generated by server)
 * - createdAt, updatedAt (server timestamps)
 */
export class UploadKeysDto {
  @ValidateNested()
  @Type(() => IdentityKeyDto)
  identityKey: IdentityKeyDto;

  @ValidateNested()
  @Type(() => SignedPreKeyDto)
  signedPreKey: SignedPreKeyDto;

  @IsArray()
  @ArrayMinSize(1, { message: 'At least one one-time pre-key is required' })
  @ValidateNested({ each: true })
  @Type(() => OneTimePreKeyDto)
  oneTimePreKeys: OneTimePreKeyDto[];
}

/**
 * DTO for claiming pre-keys
 * POST /api/keys/claim
 */
export class ClaimPreKeysDto {
  @IsUUID()
  userId: string;

  @IsOptional()
  @IsInt()
  @Min(1)
  @Max(100)
  @Type(() => Number)
  count?: number = 1;
}

/**
 * DTO for creating a session key
 * POST /api/keys/session
 *
 * Server-owned fields NOT included:
 * - userId (extracted from auth token)
 * - id (generated by server)
 * - createdAt, lastUsedAt (server timestamps)
 */
export class CreateSessionKeyDto {
  @IsUUID()
  conversationId: string;

  @IsString()
  rootKey: string;

  @IsString()
  chainKey: string;
}

/**
 * DTO for updating a session key
 * PUT /api/keys/session/:conversationId
 */
export class UpdateSessionKeyDto {
  @IsString()
  chainKey: string;

  @IsInt()
  @Min(0)
  @Type(() => Number)
  messageNumber: number;
}
