import { IsString, IsUUID, IsOptional, IsEnum, IsInt, Min, Max, MaxLength } from 'class-validator';
import { Type } from 'class-transformer';

/**
 * Gift history filter type
 */
export enum GiftHistoryType {
  SENT = 'sent',
  RECEIVED = 'received',
  ALL = 'all',
}

/**
 * DTO for sending a virtual gift
 * POST /api/gifts/send
 *
 * Server-owned fields NOT included:
 * - senderId (extracted from auth token)
 * - receiverId (determined from conversation)
 * - transactionId (generated by server)
 * - messageId (generated by server)
 * - sentAt (server timestamp)
 */
export class SendGiftDto {
  @IsUUID()
  conversationId: string;

  @IsString()
  giftId: string;

  @IsOptional()
  @IsString()
  @MaxLength(500)
  message?: string;
}

/**
 * DTO for gift history query parameters
 * GET /api/gifts/history
 */
export class GiftHistoryQueryDto {
  @IsOptional()
  @IsEnum(GiftHistoryType)
  type?: GiftHistoryType = GiftHistoryType.ALL;

  @IsOptional()
  @IsInt()
  @Min(1)
  @Max(100)
  @Type(() => Number)
  limit?: number = 50;
}
