import {
  IsString,
  IsUUID,
  IsOptional,
  IsEnum,
  IsObject,
  IsBoolean,
  MaxLength,
  MinLength,
  ValidateNested,
} from 'class-validator';
import { Type } from 'class-transformer';
import { MessageType, MessageStatus } from '../types';

/**
 * Metadata for media messages (images, videos, audio, files)
 */
export class MessageMetadataDto {
  @IsOptional()
  @IsString()
  @MaxLength(2048)
  mediaUrl?: string;

  @IsOptional()
  @IsString()
  @MaxLength(2048)
  thumbnailUrl?: string;

  @IsOptional()
  @Type(() => Number)
  duration?: number;

  @IsOptional()
  @Type(() => Number)
  fileSize?: number;

  @IsOptional()
  @IsString()
  @MaxLength(255)
  fileName?: string;

  @IsOptional()
  @IsString()
  @MaxLength(100)
  mimeType?: string;
}

/**
 * DTO for sending a new message
 * POST /api/messages
 *
 * Server-owned fields NOT included:
 * - id (generated by server)
 * - senderId (extracted from auth token)
 * - status (set to SENT by server)
 * - sentAt (timestamp set by server)
 * - deliveredAt, readAt (set by server on status updates)
 */
export class SendMessageDto {
  @IsOptional()
  @IsUUID()
  conversationId?: string;

  @IsUUID()
  receiverId: string;

  @IsString()
  @MinLength(1)
  @MaxLength(10000)
  content: string;

  @IsOptional()
  @IsEnum(MessageType)
  type?: MessageType;

  @IsOptional()
  @ValidateNested()
  @Type(() => MessageMetadataDto)
  metadata?: MessageMetadataDto;

  @IsOptional()
  @IsUUID()
  replyTo?: string;
}

/**
 * DTO for updating a message (edit content)
 * PUT /api/messages/:messageId
 *
 * Server-owned fields NOT included:
 * - id (from URL param)
 * - senderId (validated against auth token)
 * - status, timestamps (server-managed)
 */
export class UpdateMessageDto {
  @IsUUID()
  conversationId: string;

  @IsOptional()
  @IsString()
  @MinLength(1)
  @MaxLength(10000)
  content?: string;
}

/**
 * DTO for deleting a message
 * DELETE /api/messages/:messageId
 */
export class DeleteMessageDto {
  @IsUUID()
  conversationId: string;

  @IsOptional()
  @IsBoolean()
  deleteForAll?: boolean;
}

/**
 * DTO for updating message status (delivered/read)
 * PUT /api/messages/:messageId/status
 *
 * Note: Only 'delivered' and 'read' statuses are allowed from client.
 * 'sent' and 'failed' are server-managed.
 */
export class UpdateMessageStatusDto {
  @IsUUID()
  conversationId: string;

  @IsEnum([MessageStatus.DELIVERED, MessageStatus.READ], {
    message: 'Status must be either "delivered" or "read"',
  })
  status: MessageStatus.DELIVERED | MessageStatus.READ;
}

/**
 * DTO for marking a single message as read
 * POST /api/messages/:messageId/read
 */
export class MarkMessageReadDto {
  @IsUUID()
  conversationId: string;
}
