import { IsString, IsUUID, IsOptional, IsEnum, IsArray, MaxLength } from 'class-validator';

/**
 * Report reason types
 */
export enum ReportReason {
  HARASSMENT = 'harassment',
  SPAM = 'spam',
  SCAM = 'scam',
  INAPPROPRIATE_CONTENT = 'inappropriate_content',
  IMPERSONATION = 'impersonation',
  THREATS = 'threats',
  UNDERAGE = 'underage',
  SOLICITATION = 'solicitation',
  OTHER = 'other',
}

/**
 * DTO for reporting content
 * POST /api/moderation/report
 *
 * Server-owned fields NOT included:
 * - reporterId (extracted from auth token)
 * - reportId (generated by server)
 * - status (set by server)
 * - createdAt (server timestamp)
 * - reviewedAt, reviewedBy (server-managed)
 */
export class ReportContentDto {
  @IsUUID()
  conversationId: string;

  @IsOptional()
  @IsArray()
  @IsUUID('4', { each: true })
  messageIds?: string[];

  @IsEnum(ReportReason, {
    message: 'Invalid report reason',
  })
  reason: ReportReason;

  @IsOptional()
  @IsString()
  @MaxLength(2000)
  details?: string;

  @IsOptional()
  @IsUUID()
  reportedUserId?: string;
}

/**
 * DTO for blocking a user
 * POST /api/moderation/block
 *
 * Server-owned fields NOT included:
 * - blockerId (extracted from auth token)
 * - blockedAt (server timestamp)
 */
export class BlockUserDto {
  @IsUUID()
  userId: string;

  @IsOptional()
  @IsUUID()
  conversationId?: string;
}
