apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: flamoral
type: Opaque
stringData:
  DATABASE_URL: "postgresql://dbadmin:hJW%29drAiVG5quKZuGc%7Btb-KL8smAFH8t@flamoral-prod-aurora.cluster-c456yy2skvzq.us-east-1.rds.amazonaws.com:5432/flamoral"
  JWT_SECRET: "flamoral-jwt-secret-production-v1"
  JWT_ACCESS_SECRET: "flamoral-access-secret-production-v1"
  JWT_REFRESH_SECRET: "flamoral-refresh-secret-production-v1"
  INTERNAL_SERVICE_KEY: "flamoral-internal-key-production-v1"
  REDIS_PASSWORD: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secrets
  namespace: flamoral
type: Opaque
stringData:
  JWT_SECRET: "flamoral-jwt-secret-production-v1"
  JWT_ACCESS_SECRET: "flamoral-access-secret-production-v1"
  JWT_REFRESH_SECRET: "flamoral-refresh-secret-production-v1"
  DATABASE_URL: "postgresql://dbadmin:hJW%29drAiVG5quKZuGc%7Btb-KL8smAFH8t@flamoral-prod-aurora.cluster-c456yy2skvzq.us-east-1.rds.amazonaws.com:5432/flamoral"
---
apiVersion: v1
kind: Secret
metadata:
  name: database-secrets
  namespace: flamoral
type: Opaque
stringData:
  DATABASE_URL: "postgresql://dbadmin:hJW%29drAiVG5quKZuGc%7Btb-KL8smAFH8t@flamoral-prod-aurora.cluster-c456yy2skvzq.us-east-1.rds.amazonaws.com:5432/flamoral"
