apiVersion: v1
kind: Service
metadata:
  name: workflow-engine
  namespace: flamoral
  labels:
    app: workflow-engine
    service: workflow-engine
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: ClusterIP
  ports:
  - port: 3011
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: workflow-engine
  sessionAffinity: None
---
apiVersion: v1
kind: Service
metadata:
  name: workflow-engine-headless
  namespace: flamoral
  labels:
    app: workflow-engine
    service: workflow-engine
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 3011
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: workflow-engine
