#!/bin/bash
# ============================================================================
# FLAMORAL SELF-HEALING VERIFICATION LOOP
# ============================================================================
# This script runs all quality gates and produces a verification report.
# Run with: ./scripts/verify-e2e.sh
# ============================================================================

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Results tracking
GATE_RESULTS=()
FAILED_GATES=()
TOTAL_GATES=0
PASSED_GATES=0

# Timestamp for report
TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
REPORT_DIR="./verification-reports"
REPORT_FILE="${REPORT_DIR}/verification_${TIMESTAMP}.md"

# Create report directory
mkdir -p "$REPORT_DIR"

# Function to log with timestamp
log() {
  echo -e "${BLUE}[$(date +"%H:%M:%S")]${NC} $1"
}

# Function to run a gate and track results
run_gate() {
  local gate_name="$1"
  local gate_command="$2"
  local gate_description="$3"

  TOTAL_GATES=$((TOTAL_GATES + 1))
  log "Running gate: ${YELLOW}${gate_name}${NC}"

  if eval "$gate_command" > /tmp/gate_output_${TOTAL_GATES}.txt 2>&1; then
    echo -e "  ${GREEN}PASS${NC}: $gate_name"
    GATE_RESULTS+=("PASS|$gate_name|$gate_description")
    PASSED_GATES=$((PASSED_GATES + 1))
    return 0
  else
    echo -e "  ${RED}FAIL${NC}: $gate_name"
    GATE_RESULTS+=("FAIL|$gate_name|$gate_description")
    FAILED_GATES+=("$gate_name")
    return 1
  fi
}

# Function to generate markdown report
generate_report() {
  echo "# Flamoral Verification Report" > "$REPORT_FILE"
  echo "" >> "$REPORT_FILE"
  echo "**Generated:** $(date)" >> "$REPORT_FILE"
  echo "**Result:** ${PASSED_GATES}/${TOTAL_GATES} gates passed" >> "$REPORT_FILE"
  echo "" >> "$REPORT_FILE"

  if [ ${#FAILED_GATES[@]} -eq 0 ]; then
    echo "## Status: ALL GATES PASSED" >> "$REPORT_FILE"
  else
    echo "## Status: ${#FAILED_GATES[@]} GATE(S) FAILED" >> "$REPORT_FILE"
    echo "" >> "$REPORT_FILE"
    echo "### Failed Gates:" >> "$REPORT_FILE"
    for gate in "${FAILED_GATES[@]}"; do
      echo "- $gate" >> "$REPORT_FILE"
    done
  fi

  echo "" >> "$REPORT_FILE"
  echo "## Gate Results" >> "$REPORT_FILE"
  echo "" >> "$REPORT_FILE"
  echo "| Status | Gate | Description |" >> "$REPORT_FILE"
  echo "|--------|------|-------------|" >> "$REPORT_FILE"

  for result in "${GATE_RESULTS[@]}"; do
    IFS='|' read -r status name desc <<< "$result"
    if [ "$status" = "PASS" ]; then
      echo "| :white_check_mark: PASS | $name | $desc |" >> "$REPORT_FILE"
    else
      echo "| :x: FAIL | $name | $desc |" >> "$REPORT_FILE"
    fi
  done

  echo "" >> "$REPORT_FILE"
  echo "---" >> "$REPORT_FILE"
  echo "*Report generated by Flamoral Self-Healing Verification Loop*" >> "$REPORT_FILE"
}

# ============================================================================
# STATIC GATES
# ============================================================================

echo ""
echo "============================================"
echo "  FLAMORAL VERIFICATION GATES"
echo "============================================"
echo ""

log "Starting static analysis gates..."

# Gate 1: Lock file consistency
run_gate "Lock File Consistency" \
  "test -f yarn.lock && test -f package.json" \
  "Verify yarn.lock and package.json exist"

# Gate 2: TypeScript Type Check
run_gate "TypeScript Compilation" \
  "npx tsc --noEmit 2>/dev/null || yarn tsc --noEmit 2>/dev/null" \
  "Run TypeScript compiler without emitting" || true

# Gate 3: ESLint
run_gate "ESLint Check" \
  "npx eslint apps/mobile-app/src apps/web-app/src --ext .ts,.tsx --max-warnings 0 2>/dev/null" \
  "Run ESLint with zero warnings tolerance" || true

# Gate 4: Critical file existence - Mobile
run_gate "Mobile App Config" \
  "test -f apps/mobile-app/app.config.js && test -f apps/mobile-app/eas.json" \
  "Verify mobile app configuration files exist"

# Gate 5: Critical file existence - Web
run_gate "Web App Config" \
  "test -f apps/web-app/vite.config.ts && test -f apps/web-app/vercel.json" \
  "Verify web app configuration files exist"

# ============================================================================
# MOBILE APP GATES
# ============================================================================

log "Running mobile app gates..."

# Gate 6: iOS Permission Strings
run_gate "iOS Permission Strings" \
  "grep -q 'NSCameraUsageDescription' apps/mobile-app/app.config.js && grep -q 'NSPhotoLibraryUsageDescription' apps/mobile-app/app.config.js" \
  "Verify iOS permission strings are configured"

# Gate 7: Profile Screen has loading state
run_gate "Profile Screen Loading State" \
  "grep -q 'loading\|isLoading\|ActivityIndicator' apps/mobile-app/src/screens/Main/ProfileScreen.tsx 2>/dev/null" \
  "Profile screen must have loading state (prevents infinite loader)" || true

# Gate 8: Subscription Screen has loading state
run_gate "Subscription Screen Loading State" \
  "grep -q 'loading' apps/mobile-app/src/screens/Subscription/SubscriptionScreen.tsx" \
  "Subscription screen must have loading state"

# Gate 9: Restore Purchases exists
run_gate "Restore Purchases Button" \
  "grep -q 'restorePurchases\|Restore Purchases' apps/mobile-app/src/screens/Subscription/SubscriptionScreen.tsx" \
  "Subscription screen must have restore purchases functionality"

# Gate 10: Account Deletion exists
run_gate "Account Deletion Flow" \
  "grep -q 'deleteAccount\|Delete Account' apps/mobile-app/src/screens/Settings/SettingsScreen.tsx" \
  "Settings screen must have account deletion option"

# Gate 11: Account Deletion calls API (CRITICAL)
run_gate "Account Deletion API Call" \
  "grep -E 'delete.*api|api.*delete|authApi\.deleteAccount|userApi\.deleteAccount' apps/mobile-app/src/screens/Settings/SettingsScreen.tsx 2>/dev/null" \
  "Account deletion must call actual API (not just alert)" || true

# ============================================================================
# WEB APP GATES
# ============================================================================

log "Running web app gates..."

# Gate 12: Legal pages exist
run_gate "Privacy Policy Page" \
  "test -f apps/web-app/src/pages/Legal/PrivacyPolicy.tsx" \
  "Privacy policy page must exist"

run_gate "Terms of Service Page" \
  "test -f apps/web-app/src/pages/Legal/TermsOfService.tsx" \
  "Terms of service page must exist"

# Gate 13: Vercel SPA routing
run_gate "Vercel SPA Routing" \
  "grep -q 'rewrites' apps/web-app/vercel.json 2>/dev/null" \
  "Vercel config must have SPA rewrites" || true

# Gate 14: Public routes for legal pages
run_gate "Public Legal Routes" \
  "grep -E 'privacy-policy|terms-of-service' apps/web-app/src/App.tsx | grep -v 'ProtectedRoute'" \
  "Legal pages must be public (not behind authentication)"

# ============================================================================
# SECURITY GATES
# ============================================================================

log "Running security gates..."

# Gate 15: No hardcoded secrets
run_gate "No Hardcoded Secrets" \
  "! grep -rE 'sk_live_|AKIA[0-9A-Z]{16}|-----BEGIN.*PRIVATE KEY-----' apps/ --include='*.ts' --include='*.tsx' 2>/dev/null | grep -v node_modules" \
  "No hardcoded API keys or secrets in source"

# Gate 16: No console.log with sensitive data
run_gate "No Sensitive Logs" \
  "! grep -rE 'console\.log.*password|console\.log.*token|console\.log.*secret' apps/mobile-app/src --include='*.ts' --include='*.tsx' 2>/dev/null" \
  "No logging of sensitive data" || true

# ============================================================================
# BUILD GATES
# ============================================================================

log "Running build gates..."

# Gate 17: Web build succeeds
run_gate "Web App Build" \
  "cd apps/web-app && npx tsc --noEmit 2>/dev/null" \
  "Web app TypeScript compilation" || true

# Gate 18: Mobile Expo check
run_gate "Mobile Expo Config Valid" \
  "cd apps/mobile-app && npx expo config --type introspect >/dev/null 2>&1" \
  "Expo configuration is valid" || true

# ============================================================================
# GENERATE REPORT
# ============================================================================

echo ""
echo "============================================"
echo "  VERIFICATION COMPLETE"
echo "============================================"
echo ""

generate_report

echo -e "Results: ${GREEN}${PASSED_GATES}${NC}/${TOTAL_GATES} gates passed"

if [ ${#FAILED_GATES[@]} -gt 0 ]; then
  echo ""
  echo -e "${RED}Failed gates:${NC}"
  for gate in "${FAILED_GATES[@]}"; do
    echo -e "  - ${RED}$gate${NC}"
  done
  echo ""
  echo -e "Report saved to: ${BLUE}${REPORT_FILE}${NC}"
  exit 1
else
  echo ""
  echo -e "${GREEN}All gates passed! Ready for release.${NC}"
  echo -e "Report saved to: ${BLUE}${REPORT_FILE}${NC}"
  exit 0
fi
