apiVersion: v1
kind: Secret
metadata:
  name: cosmos-secrets
  namespace: flamoral
type: Opaque
stringData:
  COSMOS_KEY: "4X7zJbr2aFwRl0NQhopFClBlN2hauADhON5yCt21mzL6h6wtR0vbWDOFoenYLlgns3JsYmDQHl33ACDbrRte2Q=="
