apiVersion: v1
kind: ConfigMap
metadata:
  name: dating-api-config
  labels:
    {{- include "dating-api.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ index .Values.env 0 "value" | default "production" | quote }}
  PORT: {{ index .Values.env 1 "value" | default "3000" | quote }}
  LOG_LEVEL: {{ index .Values.env 2 "value" | default "info" | quote }}
