apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chat-worker.fullname" . }}-config
  labels:
    {{- include "chat-worker.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.env | default (list) | first | default (dict "value" "production") | dig "value" "production" | quote }}
  WORKER_TYPE: "chat"
  LOG_LEVEL: "info"
