apiVersion: v2
name: chat-worker
description: Chat Worker Service Helm Chart
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - chat
  - worker
  - nodejs
maintainers:
  - name: Dating App Team
    email: team@flamoral.com
