replicaCount: 2

image:
  tag: "staging"

resources:
  limits:
    cpu: 800m
    memory: 768Mi
  requests:
    cpu: 400m
    memory: 384Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5

ingress:
  hosts:
    - host: api-staging.datingapp.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: api-staging-tls
      hosts:
        - api-staging.datingapp.com

env:
  - name: NODE_ENV
    value: "staging"
  - name: LOG_LEVEL
    value: "info"
