import { Knex } from 'knex';

export async function seed(knex: Knex): Promise<void> {
  // Delete existing entries
  await knex('report_categories').del();

  // Insert report categories
  await knex('report_categories').insert([
    {
      id: knex.raw('gen_random_uuid()'),
      type: 'inappropriate_photos',
      label: 'Inappropriate Photos',
      description: 'User has inappropriate, offensive, or NSFW photos',
      icon: '📷',
      is_active: true,
      display_order: 1,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: knex.raw('gen_random_uuid()'),
      type: 'inappropriate_messages',
      label: 'Inappropriate Messages',
      description: 'User sent inappropriate, offensive, or harassing messages',
      icon: '💬',
      is_active: true,
      display_order: 2,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: knex.raw('gen_random_uuid()'),
      type: 'fake_profile',
      label: 'Fake Profile',
      description: 'Profile appears to be fake, using stolen photos, or impersonating someone',
      icon: '🎭',
      is_active: true,
      display_order: 3,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: knex.raw('gen_random_uuid()'),
      type: 'spam',
      label: 'Spam',
      description: 'User is sending spam messages, advertising, or promoting external services',
      icon: '📧',
      is_active: true,
      display_order: 4,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: knex.raw('gen_random_uuid()'),
      type: 'harassment',
      label: 'Harassment',
      description: 'User is harassing, bullying, or threatening others',
      icon: '⚠️',
      is_active: true,
      display_order: 5,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: knex.raw('gen_random_uuid()'),
      type: 'underage',
      label: 'Underage User',
      description: 'User appears to be under 18 years old',
      icon: '🔞',
      is_active: true,
      display_order: 6,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: knex.raw('gen_random_uuid()'),
      type: 'scam',
      label: 'Scam or Fraud',
      description: 'User is attempting to scam, defraud, or steal money/information',
      icon: '💰',
      is_active: true,
      display_order: 7,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: knex.raw('gen_random_uuid()'),
      type: 'violence',
      label: 'Violence or Threats',
      description: 'User is promoting violence, making threats, or expressing intent to harm',
      icon: '⚔️',
      is_active: true,
      display_order: 8,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: knex.raw('gen_random_uuid()'),
      type: 'hate_speech',
      label: 'Hate Speech',
      description: 'User is using hate speech, discriminatory language, or promoting extremism',
      icon: '🚫',
      is_active: true,
      display_order: 9,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: knex.raw('gen_random_uuid()'),
      type: 'other',
      label: 'Other',
      description: 'Report doesn\'t fit into other categories',
      icon: '❓',
      is_active: true,
      display_order: 10,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
  ]);

  console.log('✓ Seeded 10 report categories');
}
